### ISSUE TITLE
Plot network of clusters

### ISSUE THREAD

**Issue by rkrug** [IPBES-Data/IPBES_TCA_Ch3_clusters#1]
@yanisica @niamir @Stokpaardje 

 I would need some help. At the TAM it was decided that one task is to run a snowball search for the key papers describing each cluster of Ch 3 and to determine the overlap of the literature between these corpi. That is the easy part. You can see the results at https://github.com/IPBES-Data/IPBES_TCA_Ch3_clusters - download snowball.html. Now my problem: How can I plot this nicely to see the differences and overlap?

My idea:
One plot per level of (see html Links between clusters for a description what these are), size of node reflects number of nodes in the cluster, one arrow in each direction where the width corresponds to the number of papers in this link.
See https://github.com/IPBES-Data/IPBES_TCA_Ch3_clusters/blob/a0e27fcb8fea732d87ad20df47eef0084c462d35/snowball.qmd#L325-L326
for my attempt. 

Has somebody any idea  how I can do this quickly?  It can be beautified at a later stage - but one should see both arrows going in both directions between nodes.?

**Comment by niamir** [comment]
@rkrug 
I would go for a table instead of plot, rows -> key papers, columns -> clusters , values ->number of extended papers fall under each cluster

**Comment by niamir** [comment]
For example if key paper 1 snowball returns 500 papers and 10 of these overlaps with cluster 2, add 10 for cluster 2

**Comment by rkrug** [comment]
So essentially like this table in the report:

<img width="1228" alt="Screenshot 2024-02-28 at 11 06 35" src="https://github.com/IPBES-Data/IPBES_TCA_Ch3_clusters/assets/487172/5a405ad4-c783-447b-b47c-f18ae184907b">

**Comment by rkrug** [comment]
I do not think it is necessary to go to keypaper level yet and for all in the first column - I think the cluster is sufficient for the first look.

**Comment by niamir** [comment]
If the idea is to just calculate overlap of of clusters, then matrix of clusters would serve the purpose. 
I thought by "overlap of the literature between these corpi" you mean by key papers.

**Comment by niamir** [comment]
In this case a chord diagram would be great

**Comment by rkrug** [comment]
Great Idea - I am looking int this https://r-graph-gallery.com/chord-diagram-interactive.html at the moment.

**Comment by rkrug** [comment]
Please check https::/doi.org/10.5751/ES-10214-230246 - I used interactive chord-diagrams.

**Comment by rkrug** [comment]
IOmplemented chord diagrams in commit https://github.com/IPBES-Data/IPBES_TCA_Ch3_clusters/commit/5c704db46a01daae40308b4f97f0a20294305782
